
delete acctinfo
delete addressinfo
delete contactinfo
delete emplinfo
delete expenseinfo
delete identityinfo
delete personalinfo
delete refinfo
delete sequence
delete employer
delete LoanComaker
delete LoanAss
delete LoanAssFinInfo
delete LoanAssMonExp
delete LoanAppv
delete LoanCancel
delete LoanCharge
delete LoanReject
delete LoanRelease
delete Loan
delete LoanClassCharge
delete EntityLoanClass
delete LoanClass
delete [Group]
delete entity

delete T_LoanType
delete T_AccountType